name: heart-disease-predictor
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - mamba=2.1.1
  - pandas=2.3.3
  - matplotlib=3.9.*
  - numpy=1.26.*
  - scikit-learn=1.7.2
  - pandera=0.26.1
  - quarto=1.8.26
  - altair-all=5.*
  - click=8.3.1
  - make=4.4.1
  - pytest=9.0.2
  - requests=2.32.5
  - jupyter=1.1.*