name: Heart-Disease-Predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-lock
  - altair-all=5.4.*
  - jupyterlab
  - vega_datasets
  - ipykernel
  - scipy
  - nb_conda_kernels
  - matplotlib>=3.2.2
  - scikit-learn
  - pandas
