name: heart-disease-predictor
channels:
- conda-forge
dependencies:
- conda=25.7.0
- mamba=2.1.1
- python=3.11.14
- pandas=2.3.3
- scikit-learn=1.7.2
- nb_conda_kernels=2.5.1
- altair-all=6.0.0
- matplotlib=3.10.8
- conda-lock=3.0.4
- pandera=0.26.1
- deepchecks=0.3.2